[package]
name = "quiver-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
quiver-core = { path = "../quiver-core" }

[[bin]]
name = "file_format"
path = "fuzz_targets/file_format.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
